mysql:
  host: localhost
  user: yourusername
  password: yourpassword
  port: mysqlport

redis:
  host: redis_host_name
  db: 0 or dbasenumber
  user: default or redis_user_name
  password: redis_password
  port: redis_port
